import {
  Transaction,
  WalletBalance,
  RiskControl,
  ExistenceProcedure,
  WalletTrace,
} from "./types";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    txid: "3f57ac655e37541fd8b3b4222319233cdb26627bba717f624102f2c04a9ed61a",
    fromAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    toAddress: "327d7txqgSrbvm59rCDAF3BSvmDXD7hz1h",
    valueBTC: 0.1,
    date: "2024-04-15T23:59:00Z",
    walletSource: "Ledger Nano",
    transactionType: "Movement",
    status: "verified",
    blockConfirmations: 45230,
    blockHeight: 735201,
  },
  {
    id: "2",
    txid: "353b4ebb5ae7a7e44ea0a475324f75952e2e3d9accd1f6e85b8bff71abefb8c5",
    fromAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    toAddress: "327d7txqgSrbvm59rCDAF3BSvmDXD7hz1h",
    valueBTC: 100.0,
    date: "2024-04-15T23:59:00Z",
    walletSource: "Ledger Nano",
    transactionType: "Movement",
    status: "verified",
    blockConfirmations: 45228,
    blockHeight: 735203,
  },
  {
    id: "3",
    txid: "697837afea3528629fdcf3da158c462c15c242e179fa83a4fd423e6e5961de45",
    fromAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    toAddress: "3DSfVKodqejb3DyKyjMJAua35DzbWivd3A",
    valueBTC: 100.0,
    date: "2024-04-15T23:59:00Z",
    walletSource: "Ledger Nano",
    transactionType: "Movement",
    status: "verified",
    blockConfirmations: 45225,
    blockHeight: 735206,
  },
  {
    id: "4",
    txid: "fc5bf66db83c128fdb25c4bb26f25c946f6eb0213f4db0d6a99711e7b249fd84",
    fromAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    toAddress: "37khhuajAHDjpuW4r8iadDPqZhfKyvt5Pq",
    valueBTC: 0.1,
    date: "2024-07-05T23:59:00Z",
    walletSource: "Ledger Nano",
    transactionType: "Movement",
    status: "verified",
    blockConfirmations: 33102,
    blockHeight: 747329,
  },
  {
    id: "5",
    txid: "027c62d9a534e9cd621ea08fc56697fdcd4f29168224504c30e055a04c3515c9",
    fromAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    toAddress: "3BXurVV679qqQTaQQL5BjUaXs3J1AVEdnu",
    valueBTC: 99.8989,
    date: "2024-07-05T23:59:00Z",
    walletSource: "Ledger Nano",
    transactionType: "Movement",
    status: "verified",
    blockConfirmations: 33098,
    blockHeight: 747333,
  },
  {
    id: "6",
    txid: "2521b2c1e76f5a06d33743951709aa909abf049ebc2bb204f5ecfdff521f23e4",
    fromAddress: "327d7txqgSrbvm59rCDAF3BSvmDXD7hz1h",
    toAddress: "3Nsg75XLMsLRMKJpy636wyjPWer3EFGJ3v",
    valueBTC: 200.0989,
    date: "2024-11-15T23:59:00Z",
    walletSource: "Ledger Nano",
    transactionType: "Movement",
    status: "pending",
    blockConfirmations: 0,
  },
  {
    id: "7",
    txid: "ab0c8a7cc9d8b9f947e50476a66b9cd6e4a47ce09cff1fed4dd4a89ca6e0eca5",
    fromAddress: "327d7txqgSrbvm59rCDAF3BSvmDXD7hz1h",
    toAddress: "3MweqZaAmaP3kY3yW1LNCATqJHv8D6HCuW",
    valueBTC: 50.0,
    date: "2025-01-10T23:59:00Z",
    walletSource: "Ledger Nano",
    transactionType: "Movement",
    status: "unverified",
  },
  {
    id: "8",
    txid: "48d5e18fd509d2993bdeea4aed037d01c025ec07acbb6fc2774449f8e8ae9b71",
    fromAddress: "3BXurVV679qqQTaQQL5BjUaXs3J1AVEdnu",
    toAddress: "3QB9EERLx1EggcuK9zLRoAw2E1RLdUMnp6",
    valueBTC: 99.8989,
    date: "2024-12-01T23:59:00Z",
    walletSource: "Ledger Nano",
    transactionType: "Movement",
    status: "verified",
    blockConfirmations: 12453,
    blockHeight: 767978,
  },
  {
    id: "9",
    txid: "c315d26a09eaa5fa86f3499e225eddd87c7ed65380a33ac74b17902f195f23af",
    fromAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    toAddress: "356cCJqdZp2fXhGU5eW1EYXfDcaUZuZeZc",
    valueBTC: 0.1,
    date: "2024-07-05T23:59:00Z",
    walletSource: "Ledger Nano",
    transactionType: "Movement",
    status: "failed",
  },
  {
    id: "10",
    txid: "ef330e22cfc7421f55f30207bc5053e78d987eecf457be823f33a7bd8974259a",
    fromAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    toAddress: "36GBBgEGPYoQeZMnWZLT4VdFgKbw4S1VfQ",
    valueBTC: 0.1,
    date: "2024-07-05T23:59:00Z",
    walletSource: "Ledger Nano",
    transactionType: "Movement",
    status: "verified",
    blockConfirmations: 33080,
    blockHeight: 747351,
  },
];

export const mockBalances: WalletBalance[] = [
  {
    id: "1",
    address: "327d7txqgSrbvm59rCDAF3BSvmDXD7hz1h",
    seedLabel: "Seed V_06",
    expectedBalance: 0.0,
    actualBalance: 0.0,
    currency: "BTC",
    asOfDate: "2024-12-31",
    status: "matched",
    variance: 0,
  },
  {
    id: "2",
    address: "3BXurVV679qqQTaQQL5BjUaXs3J1AVEdnu",
    seedLabel: "Seed V_12",
    expectedBalance: 0.0,
    actualBalance: 0.0,
    currency: "BTC",
    asOfDate: "2024-12-31",
    status: "matched",
    variance: 0,
  },
  {
    id: "3",
    address: "3Nsg75XLMsLRMKJpy636wyjPWer3EFGJ3v",
    seedLabel: "Seed V_07",
    expectedBalance: 200.0989,
    actualBalance: 200.0989,
    currency: "BTC",
    asOfDate: "2024-12-31",
    status: "matched",
    variance: 0,
  },
  {
    id: "4",
    address: "3QB9EERLx1EggcuK9zLRoAw2E1RLdUMnp6",
    seedLabel: "Seed V_13",
    expectedBalance: 99.8989,
    actualBalance: 99.8989,
    currency: "BTC",
    asOfDate: "2024-12-31",
    status: "matched",
    variance: 0,
  },
  {
    id: "5",
    address: "37khhuajAHDjpuW4r8iadDPqZhfKyvt5Pq",
    seedLabel: "Seed V_12",
    expectedBalance: 0.1,
    actualBalance: 0.1,
    currency: "BTC",
    asOfDate: "2024-12-31",
    status: "matched",
    variance: 0,
  },
  {
    id: "6",
    address: "3DSfVKodqejb3DyKyjMJAua35DzbWivd3A",
    seedLabel: "Seed V_06",
    expectedBalance: 100.0,
    actualBalance: 99.9998,
    currency: "BTC",
    asOfDate: "2024-12-31",
    status: "mismatched",
    variance: -0.0002,
  },
  {
    id: "7",
    address: "3ExKprfpFH2ocZdFKUHAxuFgnzG277",
    seedLabel: "Seed V_06 Change",
    expectedBalance: 0.0,
    actualBalance: null,
    currency: "BTC",
    asOfDate: "2024-12-31",
    status: "pending",
    variance: null,
  },
  {
    id: "8",
    address: "36GBBgEGPYoQeZMnWZLT4VdFgKbw4S1VfQ",
    seedLabel: "Seed V_01",
    expectedBalance: 0.1,
    actualBalance: 0.1,
    currency: "BTC",
    asOfDate: "2024-12-31",
    status: "matched",
    variance: 0,
  },
];

export const mockTraces: WalletTrace[] = [
  {
    id: "1",
    fromWallet: "Seed V_01",
    toWallet: "Seed V_06",
    txid: "3f57ac...d61a",
    amount: 0.1,
    date: "2024-04-15",
    traceDepth: 0,
    changeAddress: "3H2uG5...FE",
  },
  {
    id: "2",
    fromWallet: "Seed V_01",
    toWallet: "Seed V_06",
    txid: "353b4e...b8c5",
    amount: 100.0,
    date: "2024-04-15",
    traceDepth: 0,
    changeAddress: "3FfNq7...Ry",
  },
  {
    id: "3",
    fromWallet: "Seed V_06",
    toWallet: "Seed V_07",
    txid: "2521b2...23e4",
    amount: 200.0989,
    date: "2024-11-15",
    traceDepth: 1,
    changeAddress: "3ExKpr...77",
  },
  {
    id: "4",
    fromWallet: "Seed V_01",
    toWallet: "Seed V_12",
    txid: "fc5bf6...fd84",
    amount: 0.1,
    date: "2024-07-05",
    traceDepth: 0,
    changeAddress: "328TEB...hS",
  },
  {
    id: "5",
    fromWallet: "Seed V_12",
    toWallet: "Seed V_12",
    txid: "027c62...15c9",
    amount: 99.8989,
    date: "2024-07-05",
    traceDepth: 1,
  },
  {
    id: "6",
    fromWallet: "Seed V_12",
    toWallet: "Seed V_13",
    txid: "48d5e1...9b71",
    amount: 99.8989,
    date: "2024-12-01",
    traceDepth: 2,
    changeAddress: "38yzpg...fK",
  },
  {
    id: "7",
    fromWallet: "Seed VX01",
    toWallet: "Seed V_01",
    txid: "443480...d9f9",
    amount: 500.0,
    date: "2024-03-01",
    traceDepth: 0,
    changeAddress: "3BkRFS...DB",
  },
  {
    id: "8",
    fromWallet: "Seed V_06",
    toWallet: "Seed V_07",
    txid: "ab0c8a...ca5",
    amount: 50.0,
    date: "2025-01-10",
    traceDepth: 1,
  },
];

export const mockRiskControls: RiskControl[] = [
  {
    id: "1",
    riskId: "R1",
    riskDescription:
      "Private keys are revealed to the network through transaction signing or broadcasting",
    controlId: "C1",
    controlDescription:
      "Elliptic Curve Cryptography (ECC) does not reveal the signer's private key to the network. ECC allows the recipient or any other network node to validate the authenticity of a transaction without knowing the signer's private key.",
    procedureDescription:
      "Examined transaction details on the main network to confirm no private key information was transmitted or necessary to validate authenticity.",
    status: "effective",
    lastTested: "2024-12-15",
  },
  {
    id: "2",
    riskId: "R2",
    riskDescription:
      "Unauthorized or invalid transactions are validated, relayed and/or recorded to the ledger",
    controlId: "C2",
    controlDescription:
      "Only transactions signed with the appropriate private key are accepted by the network. If any transaction details in a message are changed, the transaction is rejected as invalid.",
    procedureDescription:
      "Executed transactions to determine whether: (1) appropriately signed transaction was accepted; (2) transaction signed with invalid private key was rejected; (3) signed transaction with manipulated details was detected and rejected.",
    status: "effective",
    lastTested: "2024-12-15",
  },
  {
    id: "3",
    riskId: "R2",
    riskDescription:
      "Unauthorized or invalid transactions are validated, relayed and/or recorded to the ledger",
    controlId: "C3",
    controlDescription:
      "If a public address has insufficient digital assets to execute a transaction, the transaction is rejected as invalid.",
    procedureDescription:
      "Executed transactions to determine whether: (1) signed transaction from address with sufficient assets was accepted; (2) signed transaction from address with insufficient assets was rejected.",
    status: "effective",
    lastTested: "2024-12-15",
  },
  {
    id: "4",
    riskId: "R3",
    riskDescription:
      "Previously validated transaction/block information is modified",
    controlId: "C4",
    controlDescription:
      "Valid blocks demonstrating proof-of-work are appended to the ledger.",
    procedureDescription:
      "Reperformed proof-of-work verification by assessing whether the double-hashed combination of block data and relayed nonce produced a valid block hash below the difficulty target.",
    status: "effective",
    lastTested: "2024-12-15",
  },
  {
    id: "5",
    riskId: "R3",
    riskDescription:
      "Previously validated transaction/block information is modified",
    controlId: "C5",
    controlDescription:
      "Each block is linked to the previous block through SHA-256 hashing. Changes to a block would alter all subsequent blocks, requiring proof-of-work to be re-performed.",
    procedureDescription:
      "Recalculated block header using SHA-256 and verified that altering the previous block's hash produced a substantially different block header.",
    status: "effective",
    lastTested: "2024-12-15",
  },
  {
    id: "6",
    riskId: "R4",
    riskDescription: "Ledger data is not agreed upon by the network",
    controlId: "C6",
    controlDescription:
      "Transaction details are automatically recorded when the transaction is included in a block appended to the ledger.",
    procedureDescription:
      "Examined transaction details in a network environment and noted that all key transaction details were automatically recorded in the ledger.",
    status: "effective",
    lastTested: "2024-12-15",
  },
  {
    id: "7",
    riskId: "R4",
    riskDescription: "Ledger data is not agreed upon by the network",
    controlId: "C7",
    controlDescription:
      "Full nodes autonomously maintain a copy of the blockchain ledger, continuously reconciled to copies maintained by network peers.",
    procedureDescription:
      "Compared sample of block hashes between our node and multiple third-party public block explorers. SHA-256 hash agreement confirms identical historical ledger data.",
    status: "in_progress",
    lastTested: "2024-12-10",
    notes: "Awaiting final comparison with third block explorer",
  },
  {
    id: "8",
    riskId: "R5",
    riskDescription:
      "Digital Signature Verification does not function as designed",
    controlId: "C8",
    controlDescription:
      "The blockchain protocol effectively manages Digital Signature functionality and appropriately returns verification data from the public and private key pair.",
    procedureDescription:
      "Performed digital signature verification on a controlled node with a controlled address.",
    status: "not_tested",
  },
];

export const mockProcedures: ExistenceProcedure[] = [
  {
    id: "1",
    category: "Blockchain Verification",
    procedure: "Node Synchronization Check",
    description:
      "Verify that the audit node is fully synchronized with the blockchain network and contains the complete transaction history.",
    status: "complete",
    completedDate: "2024-12-01",
    evidence: "Node sync log, block height comparison screenshot",
  },
  {
    id: "2",
    category: "Blockchain Verification",
    procedure: "Block Explorer Cross-Reference",
    description:
      "Cross-reference a sample of block hashes between the audit node and at least three independent block explorers.",
    status: "complete",
    completedDate: "2024-12-05",
    evidence: "Block hash comparison spreadsheet",
  },
  {
    id: "3",
    category: "Transaction Testing",
    procedure: "Transaction Existence Verification",
    description:
      "For each sampled transaction, verify its existence on the blockchain by querying the transaction ID and confirming it appears in a valid block.",
    status: "in_progress",
    evidence: "Transaction verification report (partial)",
    notes: "18 of 26 transactions verified",
  },
  {
    id: "4",
    category: "Transaction Testing",
    procedure: "Digital Signature Verification",
    description:
      "Verify that digital signatures on sampled transactions are valid using the corresponding public keys.",
    status: "in_progress",
    notes: "Running verification scripts",
  },
  {
    id: "5",
    category: "Balance Testing",
    procedure: "Year-End Balance Reconciliation",
    description:
      "Reconcile year-end wallet balances reported by the entity against balances derived from blockchain transaction history.",
    status: "not_started",
  },
  {
    id: "6",
    category: "Balance Testing",
    procedure: "UTXO Set Verification",
    description:
      "Verify that the unspent transaction outputs (UTXOs) for each audited address match the expected balances at the reporting date.",
    status: "not_started",
  },
  {
    id: "7",
    category: "Wallet Tracing",
    procedure: "Wallet Ownership Confirmation",
    description:
      "Confirm wallet ownership through digital signature verification or entity-provided proof of control documentation.",
    status: "complete",
    completedDate: "2024-12-10",
    evidence: "Signed messages from all entity-controlled addresses",
  },
  {
    id: "8",
    category: "Wallet Tracing",
    procedure: "Change Address Mapping",
    description:
      "Map all change addresses generated from sampled transactions back to entity-controlled wallets.",
    status: "in_progress",
    notes: "Tracing change addresses for Q3/Q4 transactions",
  },
  {
    id: "9",
    category: "Existence & Control",
    procedure: "Private Key Control Assessment",
    description:
      "Assess the entity's controls over private key management, including storage, access controls, and backup procedures.",
    status: "not_started",
  },
  {
    id: "10",
    category: "Existence & Control",
    procedure: "Multi-Signature Wallet Verification",
    description:
      "For multi-sig wallets, verify the configuration and confirm the required number of signers and their identities.",
    status: "blocked",
    notes: "Awaiting entity's multi-sig policy documentation",
  },
  {
    id: "11",
    category: "Reporting",
    procedure: "Audit Evidence Package Assembly",
    description:
      "Compile all audit evidence including transaction verifications, balance reconciliations, and control test results into the final audit workpaper.",
    status: "not_started",
  },
  {
    id: "12",
    category: "Reporting",
    procedure: "Exception and Variance Documentation",
    description:
      "Document all exceptions, variances, and anomalies identified during testing with explanations and resolution status.",
    status: "not_started",
  },
];
